### ISSUE TITLE
test issue 8

### ISSUE THREAD

**Issue by ghost** [blackchoey/test-actions#8] opened 2019-10-30 02:12 UTC
abcde

**Comment by blackchoey** [comment] 2019-11-04 08:20
test

**Comment by blackchoey** [comment] 2019-11-05 01:21
@chyuanmsft test message

**Comment by ghost** [comment] 2019-11-05 01:27
thanks a lot

**Comment by blackchoey** [comment] 2019-11-05 01:50
Duplicate of #1

**Comment by blackchoey** [comment] 2019-11-05 01:50
Duplicate of #2

**Comment by blackchoey** [comment] 2019-11-05 04:50
test

**Closed as completed** 2019-11-14 00:02 UTC
Labels: dependency, no-issue-activity
